[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
board_build.partitions = partitions.csv
monitor_speed = 921600
lib_deps =
    adafruit/Adafruit NeoPixel @ ^1.12.0

build_flags =
    -DCORE_DEBUG_LEVEL=0
build_src_filter = +<*> -<browser/>
extra_scripts = pre:../tools/embed_web.py

[env:native]
platform = native
test_framework = unity
test_filter = test_*
test_build_src = yes
build_src_filter = +<core/*.cpp> +<browser/*.cpp>
extra_scripts = pre:../tools/embed_web.py
